name: Build RPM and DEB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y rpm dpkg-dev

    - name: Prepare rpmbuild tree
      run: |
        mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
        cp rpmbuild/SOURCES/* ~/rpmbuild/SOURCES/
        cp rpmbuild/SPECS/* ~/rpmbuild/SPECS/

    - name: Build DEB
      run: |
        dpkg-deb --build debbuild countfiles.deb
        ls -l

    - name: Build RPM
      run: |
        rpmbuild -bb ~/rpmbuild/SPECS/count_etc_files.spec
        ls -l ~/rpmbuild/RPMS/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: |
          *.deb
          ~/rpmbuild/RPMS/**/*.rpm
